### ISSUE TITLE
Test suite compilation failure

### ISSUE THREAD

**Issue by snoyberg** [chrisdone/path#54]
```
> /tmp/stackage-build13/path-0.5.11$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup configure --enable-tests --package-db=clear --package-db=global --package-db=/var/stackage/work/builds/nightly/pkgdb --libdir=/var/stackage/work/builds/nightly/lib --bindir=/var/stackage/work/builds/nightly/bin --datadir=/var/stackage/work/builds/nightly/share --libexecdir=/var/stackage/work/builds/nightly/libexec --sysconfdir=/var/stackage/work/builds/nightly/etc --docdir=/var/stackage/work/builds/nightly/doc/path-0.5.11 --htmldir=/var/stackage/work/builds/nightly/doc/path-0.5.11 --haddockdir=/var/stackage/work/builds/nightly/doc/path-0.5.11 --flags=
Configuring path-0.5.11...
> /tmp/stackage-build13/path-0.5.11$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup build
Building path-0.5.11...
Preprocessing library path-0.5.11...
[1 of 2] Compiling Path.Internal    ( src/Path/Internal.hs, dist/build/Path/Internal.o )
[2 of 2] Compiling Path             ( src/Path.hs, dist/build/Path.o )
Preprocessing test suite 'test' for path-0.5.11...
[1 of 2] Compiling Path.Gen         ( test/Path/Gen.hs, dist/build/test/test-tmp/Path/Gen.o )

test/Path/Gen.hs:55:10: error:
    Not in scope: type constructor or class ‘GenValidity’
    Perhaps you meant one of these:
      ‘Validity’ (imported from Data.GenValidity),
      ‘GenValid’ (imported from Data.GenValidity)

test/Path/Gen.hs:58:10: error:
    Not in scope: type constructor or class ‘GenValidity’
    Perhaps you meant one of these:
      ‘Validity’ (imported from Data.GenValidity),
      ‘GenValid’ (imported from Data.GenValidity)

test/Path/Gen.hs:61:10: error:
    Not in scope: type constructor or class ‘GenValidity’
    Perhaps you meant one of these:
      ‘Validity’ (imported from Data.GenValidity),
      ‘GenValid’ (imported from Data.GenValidity)

test/Path/Gen.hs:64:10: error:
    Not in scope: type constructor or class ‘GenValidity’
    Perhaps you meant one of these:
      ‘Validity’ (imported from Data.GenValidity),
      ‘GenValid’ (imported from Data.GenValidity)
```

**Comment by NorfairKing** [comment]
Fix is on its way.

**Comment by NorfairKing** [comment]
To be clear: the fix will be an upper-bound on the version of this library.

**Comment by snoyberg** [comment]
FTR, that won't help for the Stackage build failures.

**Comment by NorfairKing** [comment]
@snoyberg The reason is that genvalidity 0.3 requires `TypeApplications` and this is not available for GHC 7.10

**Comment by snoyberg** [comment]
I don't know about any of that, but I discovered this with a Stackage build with GHC 8.0.2, and we're not likely to roll back a package due to a test suite upper bound, but instead skip the test suite entirely.

**Comment by NorfairKing** [comment]
@snoyberg, I could upgrade the test, but then the test suite will only run with base >= 4.9. Is that better?

**Comment by NorfairKing** [comment]
@chrisdone Any input?

**Comment by mrkkrp** [comment]
You can't make your package compile with more than one version of GHC? Also, I don't understand, if this `genvalitidy` thing requires `TypeApplications` to work (which is not nice for users of older GHC versions, would be OK for a hobby project, but from industrial libraries I'd expect more backward-compatible solutions), then why does it fail with GHC 8.0.2? Is there a setup it works fine with at all? I ask because I use `path` and rely on it, so I do care what happens to the project.

I'd suggest testing with Cabal as well. I use Stack exclusively, but for testing Cabal may be better (or it might complement Stack tests), since this way you can test with GHC versions that are not yet supported by Stack, and test with newer versions of libraries/test in more adverse conditions. If a package compiles with Cabal, then surely it won't have problems getting into Stackage snapshots. Of course it would be nice to have compatibility with at least 3 latest GHC releases.

I'd expect test suite to compile and pass with every setup library itself compiles.

**Comment by NorfairKing** [comment]
@mrkkrp,

Some explanation
Version `0.2` of `genvalidity-hspec` does not use `TypeApplications` but `0.3` does.
These tests are built for version `0.2` but `0.3` is (trying to be) in stackage.

`TypeApplications` is essential in the design of `genvalidity-hspec`.

> I'd expect test suite to compile and pass with every setup library itself compiles.

That's fair, but a choice has to be made:

- Get `genvalidity-*" out of stackage.
- Get this test suite out of stackage 
- Make this test suite only compile with `ghc-8.0`.

**Comment by chrisdone** [comment]
I'm fine with making _this part_ of the test suite dependent on GHC 8. We move the genvalidity tests into a separate test suite with that condition and we should be ok. If testing on an older version of GHC, we only have the hspec-based test which I'm fine with. Is that good?

**Comment by NorfairKing** [comment]
@chrisdone That sounds like a great compromise.

I'll make a PR for that if you'd like.

**Comment by chrisdone** [comment]
Great thanks!

**Comment by chrisdone** [comment]
@snoyberg the genvalidity tests are now enabled with a flag.

**Comment by NorfairKing** [comment]
Note that the tests should compile (and pass) on the latest stackage.
